config/routes.rb
Rails.application.routes.draw do
  unless Rails.env.test?
    devise_for :users
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'home#index'

  # routes for MVC

  resources :inventories, only: %i[index show new create destroy]

  resources :recipes, only: %i[index show new create destroy]

  resources :public_recipes, only: [:index]

  resources :foods, only: %i[new create destroy]

  resources :recipe_foods, only: %i[new create destroy edit update]

  resources :inventory_foods, only: %i[new create destroy]

  # Create Route for Shopping List
  get '/shopping_lists', to: 'shopping_lists#index', as: 'shopping_lists'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :destroy

  validates :name, presence: true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @user = current_user
    @inventories = @user.inventories
  end

  def show
    @user = current_user
    @inventory = Inventory.includes(inventory_foods: :food).find(params[:id])
    @inventory_foods = @inventory.inventory_foods
  end

  def new
    @user = current_user
    @inventory = @user.inventories.new
  end

  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.user = current_user
    if @inventory.save
      redirect_to @inventory, notice: 'Inventory successfully created.'
    else
      render :new, alert: 'Inventory not created.'
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    if @inventory.destroy
      redirect_to inventories_path, notice: 'Inventory successfully deleted.'
    else
      redirect_to inventories_path, alert: 'Inventory not deleted.'
    end
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/index.html.erb
<div id="inventories">
<h1 id="inventories-heading">Inventories</h1>
<hr>

<button id="new-inventory-button">
<%= link_to 'New Inventory', new_inventory_path, id: "new-inventory" %>
</button>

<% if @inventories.empty? %>
    <div>
        <h3 class="text-center">No inventories yet.</h3>
    </div>
<% else %>

    <% @inventories.each_with_index do |inventory, index| %>
        <div class="inventory">
        <div class="inventory-main-info">
        <div class="inventory-heading">
        <h2>Inventory <%= index + 1 %></h2>
        </div>
            <div class="inventory-name">
                <h3><%= inventory.name %></h3>
            </div>
            <div class="inventory-actions">
                <button class="btn btn-primary">
                    <%= link_to 'Show', inventory_path(inventory) %>
                </button>
                <button class="btn btn-danger">
                    <%= link_to 'Delete', inventory_path(inventory), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, method: :delete %>
                </button>
            </div>
        </div>
            <div class="inventory-description">
                <p>Offered say visited elderly and. Waited period are played family man formed. He ye body or made on pain part meet. You one delay nor begin our folly abode. By disposed replying mr me unpacked no. As moonlight of my resolving unwilling.</p>
            </div>
        </div>
    <% end %>
<% end %>
</div>

app/views/inventories/new.html.erb
<h2>Add new inventory</h2>

  <%= turbo_frame_tag @inventory do %>
    <%= form_with model: @inventory do |form| %>
      <% if @inventory.errors.any? %>
        <div role="alert">
          <% @inventory.errors.full_messages.each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
      <% end %>
      <div>
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" , required: true %>
      </div>

      <%= form.submit "Create", data: { turbo: false }, class: "btn btn-primary" %>
    <% end %>
  <% end %>

app/views/inventories/show.html.erb
<%if @inventory.user == current_user %>
<h1 class="show-inventory-heading">Inventory 1</h1>
    <h2 class="show-inventory-name"><%= @inventory.name %></h2>
    <button class="add-food-button">
    <%= link_to "Add food", new_inventory_food_path(inventory_id: @inventory.id) %>
    </button>
    <hr>
    
      <% if @inventory_foods.empty? %>
        <h4>No foods have been added yet.</h4>
      <% else %>

      <table>
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        <% @inventory_foods.each do | inventory_food | %>
          <tr>
        <td><div><%= inventory_food.food.name %></div></td>
        <td><div><%= inventory_food.quantity %> <%= inventory_food.food.measurement_unit %></div></td>
        <td class="action">
        <div>
        <%= link_to "Remove", inventory_food_path(inventory_id: @inventory.id, id: inventory_food.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
      </div>
        </td>
      </tr>
        <% end %>
    </tbody>
  </table>
      <% end %>
      
  <% else %>
    <h4>You are not authorized to see this inventory.</h4>
<% end %>