config/routes.rb
Rails.application.routes.draw do
  unless Rails.env.test?
    devise_for :users
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'home#index'

  # routes for MVC

  resources :inventories, only: %i[index show new create destroy]

  resources :recipes, only: %i[index show new create destroy]

  resources :public_recipes, only: [:index]

  resources :foods, only: %i[new create destroy]

  resources :recipe_foods, only: %i[new create destroy edit update]

  resources :inventory_foods, only: %i[new create destroy]

  # Create Route for Shopping List
  get '/shopping_lists', to: 'shopping_lists#index', as: 'shopping_lists'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :description, length: { maximum: 2000 }
  validates :preparation_time_hours, numericality: { greater_than_or_equal_to: 0.00 }
  validates :cooking_time_hours, numericality: { greater_than_or_equal_to: 0.00 }
  validates :public, inclusion: { in: [true, false] }, exclusion: { in: [nil] }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @user = current_user
    @recipes = @user.recipes
  end

  def show
    @user = current_user
    @recipe = Recipe.includes(recipe_foods: :food).find(params[:id])
    @recipe_foods = @recipe.recipe_foods
  end

  def new
    @user = current_user
    @recipe = @user.recipes.new
  end

  def create
    @user = current_user
    @recipe = @user.recipes.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:notice] = 'Recipe deleted.'
    else
      flash[:alert] = 'Error deleting recipe.'
    end
    redirect_to request.referrer
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time_hours, :cooking_time_hours, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div id="recipes">
<h1 id="recipes-heading">Recipes</h1>
<hr>

<button id="new-recipe-button">
<%= link_to 'New Recipe', new_recipe_path, id: "new-recipe" %>
</button>

<% if @recipes.empty? %>
    <div>
        <h3 class="text-center">No Recipes yet.</h3>
    </div>
<% else %>

    <% @recipes.each_with_index do |recipe, index| %>
        <div class="recipe">
        <div class="recipe-main-info">
        <div class="recipe-heading">
        <h2>Recipe <%= index + 1 %></h2>
        </div>
            <div class="recipe-name">
                <h3><%= recipe.name %></h3>
            </div>
            <div class="recipe-actions">
                <button class="btn btn-primary">
                    <%= link_to 'Show', recipe_path(recipe) %>
                </button>
                <button class="btn btn-danger">
                    <%= link_to 'Delete', recipe_path(recipe), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, method: :delete %>
                </button>
            </div>
        </div>
            <div class="recipe-description">
                <p>
                <%= recipe.description %>
                </p>
            </div>
        </div>
    <% end %>
<% end %>
</div>

app/views/recipes/new.html.erb
<div>
  <h2>Add new recipe:</h2>
  <%= turbo_frame_tag @recipe do %>
    <%= form_with model: @recipe do |form| %>
      <% if @recipe.errors.any? %>
        <div role="alert">
          <% @recipe.errors.full_messages.each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
      <% end %>
      <div>
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" , required: true %>
      </div>

      <div>
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control", required: true %>
      </div>

      <div>
        <%= form.label :cooking_time_hours %>
        <%= form.number_field :cooking_time_hours, step: 0.01, class: "form-control", required: true %>
      </div>

      <div>
        <%= form.label :preparation_time_hours %>
        <%= form.number_field :preparation_time_hours, step: 0.01, class: "form-control", required: true %>
      </div>

      <div>
        <%= form.label :public, class: "form-check-label" %>
        <%= form.check_box :public, class: "form-check-input" %>
      </div>

      <%= form.submit "Create", data: { turbo: false }, class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/recipes/public_recipes.html.erb
<div>
  <h1>Public Recipes</h1>
  <% if @recipes.empty? %>
    <h1>No public recipes yet.</h1>
  <% else %>
    <% @recipes.each do |recipe| %>
      <div>
        <div>
          <h3><%= link_to recipe.name, recipe_path(id: recipe.id), class: "text-dark" %></h3>
          <p>By: <%= recipe.user.name %></p>
        </div>
        <div>
          <% total_food_items(recipe.id) %>
          <p>Total food items: <%= @sub_total[0] %></p>
          <p>Total price: $<%= @sub_total[1] %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div>
<% if @recipe.public || @recipe.user == current_user %>
<h1 class="show-recipe-heading">Recipe 1</h1>
    <h2 class="show-recipe-name"><%= @recipe.name %></h2>

    <div id="recipe-details-information">
    <div class="prepare-toggle">
      <p>Preparation time: <b><%= @recipe.preparation_time_hours %> hours</b></p>

      <div>

      <% if @recipe.user == current_user %>
  <div class="toggle-container">
    <%= form_for @recipe, url: recipe_path(@recipe), method: :patch do |f| %>
      <label for="toggle">
        <b>Public</b>
      </label>
      <div class="toggle-label">
        <%= f.check_box :public, id: 'toggle', class: 'toggle-input' %>
        <%= f.label :public, class: 'toggle-label', for: 'toggle' do %>
          <div class="toggle-indicator"></div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
      
        
      </div>
    </div>
    <p>Cooking time: <b><%= @recipe.cooking_time_hours %> hours</b></p>
    <hr style="margin-top: 10px; margin-bottom: 10px;">
    <p class="fs-5"><%= @recipe.description %></p>
  </div>


  <div id="shopping-list-generate-button">
    <button type="button"
    id="generate-shopping-list"
      class="btn btn-primary"
      data-bs-toggle="modal"
      data-bs-target="#myModal"
      onclick="showModal()">
        Generate shopping list
    </button>

    

    <!-- Modal (initially hidden) -->
    <div class="custom-modal" id="myModal" style="display: none;">
      <div class="custom-modal-content card">
        <div class="custom-modal-header">
          <h5 class="custom-modal-title">Generating Shopping List</h5>
          <button type="button" class="custom-btn-close" onclick="hideModal()" aria-label="Close"></button>
        </div>
        <div class="custom-modal-body">
          <!-- Add content for your modal here -->
          <div>
  <div>
    <div>
      
      <div id="">
        <h6>Choose an inventory to use</h6>
        <%= form_with url: shopping_lists_path(recipe_id: @recipe.id), method: :get do |form| %>
          <div id="modal-input">
          <div>
          <%= select("inventory", "inventory_id", Inventory.all.collect { |p| [ p.name, p.id ] }, { prompt: 'Select Inventory' }) %>
          <%= form.number_field :recipe_id, class: "form-control", value: @recipe.id, hidden: true %>
          </div>
      <div>
        <%= form.submit "Generate", data: { turbo: false }, class: "btn btn-primary generate-submit" %>
        <% end %>
      </div>
      </div>
      </div>
    </div>
  </div>
</div>
        </div>
        <div class="custom-modal-footer">
          <button type="button" class="btn btn-secondary" onclick="hideModal()">Close</button>
          <!-- Add additional buttons or actions here -->
        </div>
      </div>
    </div>
  </div>


    

    <% if @recipe.user == current_user %>
    <button class="add-ingredient-button">
    <%= link_to "Add ingredient", new_recipe_food_path(recipe_id: @recipe.id) %>
    </button>
    <% end %>
  </div>

  
    <hr>


    
      <% if @recipe_foods.empty? %>
        <h4>No foods have been added yet.</h4>
      <% else %>

      <table>
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
        <% @inventory_foods.each do |recipe_food| %>
          <tr>
        <td><div><%= recipe_food.food.name %></div></td>
        <td><div><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></div></td>
        <td><div><b>$<%= recipe_food.food.price_dollars * recipe_food.quantity %></b></div></td>
        <td class="action">
        <div>
        <% if @recipe.user == current_user %>
        <%= link_to "Modify", edit_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), class: "btn btn-primary" %>
        <% end %>

        <% if @recipe.user == current_user %>
        <%= link_to "Remove", recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
        <% end %>
      </div>
        </td>
      </tr>
        <% end %>
    </tbody>
  </table>
      <% end %>
      
  <% else %>
    <h4>You are not authorized to see this recipe.</h4>
<% end %>
</div>


  <!-- JavaScript to handle modal visibility -->
  <script>
    function showModal() {
      document.getElementById("myModal").style.display = "block";
    }

    function hideModal() {
      document.getElementById("myModal").style.display = "none";
    }
  </script>

  <!-- Include Bootstrap JS library -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>