config/routes.rb
Rails.application.routes.draw do
  unless Rails.env.test?
    devise_for :users
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'home#index'

  # routes for MVC

  resources :inventories, only: %i[index show new create destroy]

  resources :recipes, only: %i[index show new create destroy]

  resources :public_recipes, only: [:index]

  resources :foods, only: %i[new create destroy]

  resources :recipe_foods, only: %i[new create destroy edit update]

  resources :inventory_foods, only: %i[new create destroy]

  # Create Route for Shopping List
  get '/shopping_lists', to: 'shopping_lists#index', as: 'shopping_lists'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, dependent: :destroy
  has_many :inventory_foods, dependent: :destroy

  validates :name, presence: true, length: { maximum: 250 }
  validates :measurement_unit, presence: true
  validates :price_dollars, presence: true, numericality: { greater_than: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      # redirect to the page that called this action
      redirect_to request.referer, notice: 'Food successfully created.'
    else
      render :new, alert: 'Food not created.'
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.destroy
      redirect_to root_path, notice: 'Food successfully deleted.'
    else
      redirect_to root_path, alert: 'Food not deleted.'
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price_dollars)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<h2>Add new food</h2>

    <%= form_with model: @food do |form| %>
        <% if @food.errors.any? %>
            <div>
                <% @food.errors.full_messages.each do |message| %>
                    <div><%= message %></div>
                <% end %>
            </div>
        <% end %>

        <div>
            <%= form.label :name %> <br>
            <%= form.text_field :name %>
        </div>

        <div>
            <%= form.label :measurement_unit %> <br>
            <%= form.text_field :measurement_unit %>
        </div>

        <div>
            <%= form.label :price_dollars %> <br>
            <%= form.number_field :price_dollars, step: 0.01 %>
        </div>
        <p><%= form.submit "Create", data: { turbo: false }, class: "btn btn-primary" %></p>
    <% end %>

app/views/foods/index.html.erb
<h2>Foods</h2>

<section>
  <%= link_to "Add Food", new_food_path, %>
  <%if @foods.present? %>
    <ul>
      <li>
        <div><b>Food</b></div>
        <div><b>Measurement Unit</b></div>
        <div><b>Price</b></div>
        <div><b>Actions</b></div>
      </li>
      <% @foods.each do | food | %>
        <li>
          <div><%= food.name %></div>
          <div><%= food.measurement_unit %></div>
          <div><%= food.price_dollars %></div>
          <div>
            <%= button_to "Delete", food_path(food), class: "btn btn-danger", method: :delete %>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <div>
      <p> No foods registered. </p>
    </div>
  <% end %>
</section>

app/views/foods/new.html.erb
<section class="container">
  <%= render 'foods/form' %>
</section>

app/views/foods/show.html.erb
<h1>Foods#show</h1>

<p>Name: <%= @food.name %></p>

<p>Measurement Unit: <%= @food.measurement_unit %></p>

<p>Price: <%= @food.price_dollars %></p>