config/routes.rb
Rails.application.routes.draw do
  unless Rails.env.test?
    devise_for :users
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'home#index'

  # routes for MVC

  resources :inventories, only: %i[index show new create destroy]

  resources :recipes, only: %i[index show new create destroy]

  resources :public_recipes, only: [:index]

  resources :foods, only: %i[new create destroy]

  resources :recipe_foods, only: %i[new create destroy edit update]

  resources :inventory_foods, only: %i[new create destroy]

  # Create Route for Shopping List
  get '/shopping_lists', to: 'shopping_lists#index', as: 'shopping_lists'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food

  validates :quantity, presence: true

  def self.total_price(recipe)
    recipe_foods = RecipeFood.where(recipe_id: recipe)
    price = 0
    recipe_foods.each do |recipe_food|
      Food.find(recipe_food.food_id)
      price += recipe_food.quantity * recipe_food.food.price_dollars
    end
    price
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @user = current_user
    # check if I am receiving the recipe_id in the params
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
    @foods = Food.all
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new(food_id: params[:food][:food_id], quantity: params[:quantity])
    if @recipe_food.save
      redirect_to recipe_path(@recipe), notice: 'Recipe food successfully created.'
    else
      render :new, alert: 'Recipe food not created.'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe
    if @recipe_food.destroy
      redirect_to recipe_path(@recipe), notice: 'Recipe food successfully deleted.'
    else
      redirect_to recipe_path(@recipe), alert: 'Recipe food not deleted.'
    end
  end

  def edit
    @user = current_user
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe
    @foods = Food.all
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    @recipe = @recipe_food.recipe
    if @recipe_food.update(recipe_food_params)
      redirect_to recipe_path(@recipe), notice: 'Recipe food successfully updated.'
    else
      redirect_to request.referrer, alert: 'Recipe food not updated.'
    end
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/edit.html.erb
<div>
  <h2>Edit food quantity for recipe:</h2>
  <%= form_with(model: @recipe_food, url: recipe_food_path, method: "patch") do |form| %>

    <div>
      <%= form.label :quantity %> <br>
      <%= form.number_field :quantity, class: "form-control" , required: true %>
    </div>

    <%= form.submit "Create", data: { turbo: false }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/recipe_foods/new.html.erb
<div>
  <% if current_user.id == @recipe.user_id %>
    <h2>Add new food to recipe:</h2>
    <%= form_with url: recipe_foods_path(recipe_id: @recipe) do |form| %>

      <%= select("food", "food_id", Food.all.collect { |p| [ p.name, p.id ] }, { prompt: 'Select Food' }) %>

      <div>
        <%= form.label :quantity %> <br>
        <%= form.number_field :quantity, class: "form-control" , required: true %>
      </div>

      <%= form.submit "Create", data: { turbo: false }, class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>